server:
  servlet:
    contextPath: /api
  port: 7070

spring:
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE

  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select email, role from users where email=?